version: "3.9"
services:
  jfgr-notificacao-parquimetro-fakesmtp:
    image: haravich/fake-smtp-server:latest
    ports:
      - 1025:1025 # SMTP
      - 1080:1080 # API INTERFACE
  jfgr-notificacao-parquimetro-postgresql:
    restart: always
    build:
      context: .
      dockerfile: postgresql.dockerfile
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - jfgr-notificacao-parquimetro-pgdata:/var/lib/postgresql/data
    networks:
      - jfgr-notificacao-parquimetro
networks:
  jfgr-notificacao-parquimetro:
    driver: bridge
volumes: 
  jfgr-notificacao-parquimetro-pgdata: