version: "3.9"
services:
  jfgr-api-parquimetro-postgresql:
    restart: always
    build:
      context: .
      dockerfile: postgresql.dockerfile
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - jfgr-api-parquimetro-pgdata:/var/lib/postgresql/data
    networks:
      - jfgr-api-parquimetro
networks:
  jfgr-api-parquimetro:
    driver: bridge
volumes: 
  jfgr-api-parquimetro-pgdata: