version: "3.9"
services:
  jfgr-api-parquimetro-pagamento:
    restart: always
    build: 
      context: ./../../../pagamento
      dockerfile: Dockerfile
    networks:
      - jfgr-parquimetro
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - RABBIT_HOST=${RABBIT_HOST}
      - RABBIT_PASSWORD=${RABBIT_PASSWORD}
      - RABBIT_PORT=${RABBIT_PORT}
      - RABBIT_USER=${RABBIT_USER}
      - TZ=America/Sao_Paulo
  jfgr-pagamento-parquimetro-postgresql:
    restart: always
    build:
      context: .
      dockerfile: postgresql.dockerfile
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    environment:
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - PGPORT=${POSTGRES_PORT}
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - jfgr-pagamento-parquimetro-pgdata:/var/lib/postgresql/data
    networks:
      - jfgr-parquimetro
networks:
  jfgr-parquimetro:
    external: true
volumes: 
  jfgr-pagamento-parquimetro-pgdata: